#!/bin/bash

cp ./src/components/DomainSetting/domain-setting.scss ./lib/components/DomainSetting/domain-setting.scss
cp ./src/components/UserDirectoryView/user-dir.scss ./lib/components/UserDirectoryView/user-dir.scss
cp ./src/components/ComposeViewPanels/index.scss ./lib/components/ComposeViewPanels/index.scss
cp ./src/components/Dropdown/dropdown.scss ./lib/components/Dropdown/dropdown.scss
cp ./src/components/UserCard/user-card.scss ./lib/components/UserCard/user-card.scss
cp ./src/components/DiscoverPanels/index.scss ./lib/components/DiscoverPanels/index.scss
cp ./src/components/MarkdownEditor/markdown-editor.scss ./lib/components/MarkdownEditor/markdown-editor.scss
cp ./src/components/SubdomainInput/subdomain-input.scss ./lib/components/SubdomainInput/subdomain-input.scss
cp ./src/components/PostButton/post-button.scss ./lib/components/PostButton/post-button.scss
cp ./src/components/Input/index.scss ./lib/components/Input/index.scss
cp ./src/components/RichTextEditor/rich-text-editor.scss ./lib/components/RichTextEditor/rich-text-editor.scss
cp ./src/components/PostCard/post-card.scss ./lib/components/PostCard/post-card.scss
cp ./src/components/FullScreenModal/full-screen-modal-root.scss ./lib/components/FullScreenModal/full-screen-modal-root.scss
cp ./src/components/CustomFilterView/custom-filter-view.scss ./lib/components/CustomFilterView/custom-filter-view.scss
cp ./src/components/ProfileSetting/profile-setting.scss ./lib/components/ProfileSetting/profile-setting.scss
cp ./src/components/UserPanels/user-panels.scss ./lib/components/UserPanels/user-panels.scss
cp ./src/components/AppHeader/app-header.scss ./lib/components/AppHeader/app-header.scss
cp ./src/components/HeaderButton/header-button.scss ./lib/components/HeaderButton/header-button.scss
cp ./src/components/Topic/topic.scss ./lib/components/Topic/topic.scss
cp ./src/components/SavedViewPanels/index.scss ./lib/components/SavedViewPanels/index.scss
cp ./src/components/UserView/user-view.scss ./lib/components/UserView/user-view.scss
cp ./src/components/UserView/media-view.scss ./lib/components/UserView/media-view.scss
cp ./src/components/UserView/following-view.scss ./lib/components/UserView/following-view.scss
cp ./src/components/Markup/markup.scss ./lib/components/Markup/markup.scss
cp ./src/components/Button/button.scss ./lib/components/Button/button.scss
cp ./src/components/DetailPane/detail.scss ./lib/components/DetailPane/detail.scss
cp ./src/components/MediaPickerMenuable/media-picker.scss ./lib/components/MediaPickerMenuable/media-picker.scss
cp ./src/components/Avatar/avatar.scss ./lib/components/Avatar/avatar.scss
cp ./src/components/CustomView/CustomViewPanel/custom-view-panel.scss ./lib/components/CustomView/CustomViewPanel/custom-view-panel.scss
cp ./src/components/CustomView/custom-view.scss ./lib/components/CustomView/custom-view.scss
cp ./src/components/CustomView/CustomViewHeader/custom-view-header.scss ./lib/components/CustomView/CustomViewHeader/custom-view-header.scss
cp ./src/components/ComposeView/compose.scss ./lib/components/ComposeView/compose.scss
cp ./src/components/Resizable/resizable.scss ./lib/components/Resizable/resizable.scss
cp ./src/components/SearchPanels/index.scss ./lib/components/SearchPanels/index.scss
cp ./src/components/Menuable/menu-portal.scss ./lib/components/Menuable/menu-portal.scss
cp ./src/components/Menuable/menuable.scss ./lib/components/Menuable/menuable.scss
cp ./src/components/DiscoverView/discover-view.scss ./lib/components/DiscoverView/discover-view.scss
cp ./src/components/Nav/nav.scss ./lib/components/Nav/nav.scss
cp ./src/components/Icon/icon.scss ./lib/components/Icon/icon.scss
cp ./src/components/Attachments/attachments.scss ./lib/components/Attachments/attachments.scss
cp ./src/components/Thread/thread.scss ./lib/components/Thread/thread.scss
cp ./src/components/ProfilePicture/profile-pic.scss ./lib/components/ProfilePicture/profile-pic.scss
cp ./src/components/Onboarding/onboarding.scss ./lib/components/Onboarding/onboarding.scss
